config/routes.rb
Rails.application.routes.draw do

  ##################################
  ### home
  ##################################
  root to: 'visitors#index'

  ##################################
  ### admin (Administrate)
  ##################################
  namespace :admin do

    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    #resources :users 
    #resources :organizations
    #resources :systems
    #resources :vendors
    #resources :devices
    #resources :ct_refs
    #resources :client_refs            
    root to: "users#index"
  end


  ####################
  ### visitors
  ####################
  get 'visitors/super_user_home', to: 'visitors#super_user_home'
  get 'visitors/admin_home', to: 'visitors#admin_home'
  get 'visitors/evaluator_home', to: 'visitors#evaluator_home'
  get 'visitors/vendor_home', to: 'visitors#vendor_home'
  get 'visitors/visitor_home', to: 'visitors#visitor_home'
  get 'visitors/waiting_approval_home', to: 'visitors#waiting_approval_home'
  get 'visitors/suspended_home', to: 'visitors#sustemded_home'      


  ####################
  ### client_refs
  ####################
  resources :client_refs
  # and for my children, allow me to create a new child
  resources "client_refs" do # client_ref_new_XXX_path 
  end

  ####################
  ### ct_refs
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :ct_refs
  # and for my children, allow me to create a new child
  resources "ct_refs" do # ct_ref_new_XXX_path 
  end

  
  ####################
  ### devices
  ####################
  match 'devices/:id/my_show' => 'devices#my_show', :via => :get, :as => 'device_my_show'
  resources :devices
  # and for my children, allow me to create a new child
  resources "devices" do # device_new_XXX_path 
    post :new_ct_ref                           
    post :new_client_ref
    post :new_marketing_ref
    post :new_peer_reviewed_ref
  end
  
  ####################
  ### marketing_refs
  ####################
  resources :marketing_refs
  # and for my children, allow me to create a new child
  resources "marketing_refs" do # marketing_ref_new_XXX_path 
  end

  
  ####################
  ### organizations
  ####################
  resources :organizations
  # and for my children, allow me to create a new child
  resources "organizations" do
    post :new_user                           # organization_new_user_path 
                                             # POST /organizations/:organization_id/new_user(.:format)
    post :new_vendor
    member do
      # get  :register_email_intervention      # register_email_intervention_organization_path 
      #                                        # GET /organizations/:id/register_email_intervention(.:format)
    end
  end

  ####################
  ### peer_review_refs
  ####################
  resources :peer_review_refs
  # and for my children, allow me to create a new child
  resources "peer_review_refs" do # peer_review_ref_new_XXX_path 
  end
  
  
  ####################
  ### systems
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :systems
  # and for my children, allow me to create a new child
  resources "systems" do
    post :new_organization
  end

  ##################################
  ### users
  ##################################
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}  
  # match 'users/for_approval' => 'users#for_approval', :via => :get #, :as => ''
  resources :users


  
  
  ####################
  ### vendors
  ####################
  match 'vendors/request_registration_1' => 'vendors#request_registration_1', :via => :get #, :as => ''
  match 'vendors/request_registration_2' => 'vendors#request_registration_2', :via => [:get] #, :as => ''
  match 'vendors/request_registration_3' => 'vendors#request_registration_3', :via => [:post] #, :as => ''
  match 'vendors/for_approval' => 'vendors#for_approval', :via => :get #, :as => ''
  match 'vendors/devices_for_approval' => 'vendors#devices_for_approval', :via => :get #, :as => ''  
  resources :vendors
  # and for my children, allow me to create a new child
  resources "vendors" do # maps to [vendor_my_view_path] [GET /vendors/:vendor_id/my_view] [vendors#my_view]
    get :my_view
    post :my_view
    patch :my_view
    get :my_new_device
    post :my_new_device
    get :show_for_approval
    get :approve
    get :reject
    get :suspend        
  end

  


  
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  # before_action :set_vendor, only: [:show, :edit, :update, :destroy, :show_for_approval, :approve, :reject]
  before_action :authenticate_user!
  # after_action :verify_authorized  

  ###################################
  ### index
  ###   root to: 'visitors#index' 
  ###################################
  def index
    System.uc_controller_log("1.NewVisitor", current_user, controller_path, action_name, "")
    System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    puts caller_locations(1,1)[0].label

    # if there are parameters I waant to pass them (except controller and action)
    params.delete("controller")
    params.delete("action")
    if current_user.try(:super_user?)
      redirect_to visitors_super_user_home_path(params)
    elsif current_user.try(:admin?)
      redirect_to visitors_admin_home_path(params)
    elsif current_user.try(:evaluator?)
      redirect_to visitors_evaluator_home_path(params)
    elsif current_user.try(:vendor?)
      redirect_to visitors_vendor_home_path(params)
    elsif current_user.try(:visitor?)
      redirect_to visitors_visitor_home_path(params)
    elsif current_user.try(:waiting_approval?)
      redirect_to visitors_waiting_approval_home_path(params)
    elsif current_user.try(:suspended?)
      redirect_to visitors_suspended_home_path(params)
    else
      redirect_to new_user_session_path
    end
  end
  
  ###################################
  ### GET /visitors/super_user_home
  ### helper: visitors_super_user_home_path
  ### params: {"controller"=>"visitors", "action"=>"super_user_home"}
  ### super_user_home
  ###################################
  def super_user_home
    @here = visitors_super_user_home_path
    @organization = current_user.organization
    if @organization.name == "3rdPillar"
      @vendors = Vendor.all.page(params[:page]).per(9)
      @users = User.all.page(params[:page]).per(9)
      @organizations = Organization.all.page(params[:page]).per(9)      
    else
      @vendors = @organization.vendors.page(params[:page]).per(9)
      @users = @organization.users.all.page(params[:page]).per(9)
      @organizations = []
      @organizations << @organization
     
    end

  end

  ###################################
  ### GET /visitors/visitor_home
  ### helper: visitors_visitor_home_path
  ### params: {"controller"=>"visitors", "action"=>"visitor_home"}
  ### super_user_home
  ###################################
  def visitor_home
    System.uc_controller_log("1.NewVisitor", current_user, controller_path, action_name,  "")    
    @here = visitors_visitor_home_path
    @organization = current_user.organization

    @devices = my_home_filters
  end


  ###################################
  ### GET /visitors/vendor_home
  ### helper: visitors_vendor_home_path
  ### params: {"controller"=>"visitors", "action"=>"vendor_home"}
  ### vendor_home
  ###################################
  def vendor_home
    System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    # @return_to = visitors_vendor_home_path
    @vendor = current_user.vendors[0] # there should only be 1 vendor
    @here = visitors_visitor_home_path
    @organization = current_user.organization

    @devices = my_home_filters
    
  end

  ###################################
  ### GET /visitors/evaluator_home
  ### helper: visitors_evaluator_home_path
  ### params: {"controller"=>"visitors", "action"=>"evaluator_home"}
  ###################################
  def evaluator_home
    # System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    @return_to = visitors_evaluator_home_path

    @devices = my_home_filters
    
    @vendors_for_review = Vendor.where(state: "SubmittedForReview")
    @devices_for_review = Device.where(state: "SubmittedForReview")
    @ct_refs_for_review = CtRef.where(state: "SubmittedForReview")
    @client_refs_for_review = ClientRef.where(state: "SubmittedForReview")        
  end
  

  #############################################################################################
  ### Private
  #############################################################################################
  private
  def my_home_filters

    if params[:category]
      devices = Device.where(state: "Active", category: params[:category])
    else
      devices = Device.where(state: "Active")
    end


    if params[:commit] == "Clear"
      params[:search] = nil
    end
    
    if params[:search]
      if params[:commit] == "Vendors"
        vendors = Vendor.basic_search(params[:search])
        for vendor in vendors
          devices += vendor.devices
        end
      end      
      if params[:commit] == "Devices"
        devices = Device.basic_search(params[:search])
      end      
      @search = params[:search]
    end
    if devices.class == Array
      list = Kaminari.paginate_array(devices).page(params[:page]).per(9)
    else
      list = devices.page(params[:page]).per(9)
    end

    list
  end

  
end

app/views/visitors/_registration_panel.html.erb
<div class="container">  
    <div class="panel panel-default">

      <div class="panel-heading"> 
        <h3>
	  Vendor registration
	</h3>
      </div>
      <div class="panel-body">  	
        <h5>
            If you are a connected device vendor, or if you provide a service that uses connected devices, you may wish to register your device/service. To do this, you must first register as a 'Vendor'. If approved, you can then register details of yoru device / service to this registry.
         </h5>
       
         <h4>
            <span class="btn-group-xs" role="group" aria-label="...">
              To register as a vendor, press <a class="btn btn-success" href="<%= vendors_request_registration_1_path %>">Register</a>
            </span> 
         </h4>
      </div> <!-- panel-body -->

    </div> <!-- panel --> 

</div> <!-- container -->

app/views/visitors/evaluator_home.html.erb
<% # System.uc_view_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "") %>

<div class="container">

   <span class="btn-groups" role="group" aria-label="...">


      <% length = @vendors_for_review.length %>
      <% if length == 0 %>
       <% button_class = "btn-success" %>
      <% else %>
        <% button_class = "btn-primary" %>
      <% end %>
      <a class="btn <%= button_class %>" href="<%= vendors_for_approval_path(return_to: @return_to ||= root_path) %>"
         style="margin-bottom:5px;"
         title="Press to approve outstanding vendor requests"> 
         Vendor Requests for Approval <span class="badge"><%=length%></span>
      </a>
  
      <% length = @devices_for_review.length %>
      <% if length == 0 %>
        <% button_class = "btn-success" %>
      <% else %>
        <% button_class = "btn-primary" %>
      <% end %>
      <a class="btn <%= button_class %>" href="<%= vendors_devices_for_approval_path(return_to: @return_to ||= root_path) %>"
         style="margin-bottom:5px;"
         title="Press to approve outstanding vendor's Device submissions"> 
         Devices for Approval <span class="badge"><%=length%></span>
      </a>
  

      <% length = @ct_refs_for_review.length %>
      <% if length == 0 %>
         <% button_class = "btn-success" %>
      <% else %>
         <% button_class = "btn-primary" %>
      <% end %>
      <a class="btn <%= button_class %>" href="<%= vendors_devices_for_approval_path(return_to: @return_to ||= root_path) %>"
         style="margin-bottom:5px;"
         title="Press to approve outstanding vendor's Clinical Trial Reference submissions"> 
         Clinical Trial References for Review <span class="badge"><%=length%></span>
      </a>

      <% length = @client_refs_for_review.length %>
      <% if length == 0 %>
         <% button_class = "btn-success" %>
      <% else %>
         <% button_class = "btn-primary" %>
      <% end %>
      <a class="btn <%= button_class %>" href="<%= vendors_devices_for_approval_path(return_to: @return_to ||= root_path) %>"
         style="margin-bottom:5px;"
         title="Press to approve outstanding vendor's Client Reference submissions"> 
         Client References for Review <span class="badge"><%=length%></span>
      </a>
  
   </span>  
</div> <%### div class="container"%>

<br>
<%= render :partial => "devices/index_public" %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/visitors/super_user_home.html.erb
<% System.uc_view_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "") %>

<div class="container">
  <%= render :partial => "vendors/my_list" %>
</div>

app/views/visitors/vendor_home.html.erb
<% System.uc_view_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "") %>


<% if @vendor.state == "SubmittedForReview" %>
  <div class="container">
    <%= render :partial => "vendors/waiting_for_approval" %>
  </div>
<% else %>

  <div class="container">
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      You are the registered representative for <b><%= @vendor.name %></b>.
      <a class="btn btn-success" href="<%= vendor_my_view_path(@vendor) %>">Manage my Devices</a>      
    </div>
  </div>


<% end %>
  


  <%= render :partial => "devices/index_public" %>
  

app/views/visitors/visitor_home.html.erb
<div id="registration_placeholder">
</div>  

<div class="container">
  <%= render :partial => "devices/index_public" %>
</div>