config/routes.rb
Rails.application.routes.draw do

  ##################################
  ### home
  ##################################
  root to: 'visitors#index'

  ##################################
  ### admin (Administrate)
  ##################################
  namespace :admin do

    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    #resources :users 
    #resources :organizations
    #resources :systems
    #resources :vendors
    #resources :devices
    #resources :ct_refs
    #resources :client_refs            
    root to: "users#index"
  end


  ####################
  ### visitors
  ####################
  get 'visitors/super_user_home', to: 'visitors#super_user_home'
  get 'visitors/admin_home', to: 'visitors#admin_home'
  get 'visitors/evaluator_home', to: 'visitors#evaluator_home'
  get 'visitors/vendor_home', to: 'visitors#vendor_home'
  get 'visitors/visitor_home', to: 'visitors#visitor_home'
  get 'visitors/waiting_approval_home', to: 'visitors#waiting_approval_home'
  get 'visitors/suspended_home', to: 'visitors#sustemded_home'      


  ####################
  ### client_refs
  ####################
  resources :client_refs
  # and for my children, allow me to create a new child
  resources "client_refs" do # client_ref_new_XXX_path 
  end

  ####################
  ### ct_refs
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :ct_refs
  # and for my children, allow me to create a new child
  resources "ct_refs" do # ct_ref_new_XXX_path 
  end

  
  ####################
  ### devices
  ####################
  match 'devices/:id/my_show' => 'devices#my_show', :via => :get, :as => 'device_my_show'
  resources :devices
  # and for my children, allow me to create a new child
  resources "devices" do # device_new_XXX_path 
    post :new_ct_ref                           
    post :new_client_ref
    post :new_marketing_ref
    post :new_peer_reviewed_ref
  end
  
  ####################
  ### marketing_refs
  ####################
  resources :marketing_refs
  # and for my children, allow me to create a new child
  resources "marketing_refs" do # marketing_ref_new_XXX_path 
  end

  
  ####################
  ### organizations
  ####################
  resources :organizations
  # and for my children, allow me to create a new child
  resources "organizations" do
    post :new_user                           # organization_new_user_path 
                                             # POST /organizations/:organization_id/new_user(.:format)
    post :new_vendor
    member do
      # get  :register_email_intervention      # register_email_intervention_organization_path 
      #                                        # GET /organizations/:id/register_email_intervention(.:format)
    end
  end

  ####################
  ### peer_review_refs
  ####################
  resources :peer_review_refs
  # and for my children, allow me to create a new child
  resources "peer_review_refs" do # peer_review_ref_new_XXX_path 
  end
  
  
  ####################
  ### systems
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :systems
  # and for my children, allow me to create a new child
  resources "systems" do
    post :new_organization
  end

  ##################################
  ### users
  ##################################
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}  
  # match 'users/for_approval' => 'users#for_approval', :via => :get #, :as => ''
  resources :users


  
  
  ####################
  ### vendors
  ####################
  match 'vendors/request_registration_1' => 'vendors#request_registration_1', :via => :get #, :as => ''
  match 'vendors/request_registration_2' => 'vendors#request_registration_2', :via => [:get] #, :as => ''
  match 'vendors/request_registration_3' => 'vendors#request_registration_3', :via => [:post] #, :as => ''
  match 'vendors/for_approval' => 'vendors#for_approval', :via => :get #, :as => ''
  match 'vendors/devices_for_approval' => 'vendors#devices_for_approval', :via => :get #, :as => ''  
  resources :vendors
  # and for my children, allow me to create a new child
  resources "vendors" do # maps to [vendor_my_view_path] [GET /vendors/:vendor_id/my_view] [vendors#my_view]
    get :my_view
    post :my_view
    patch :my_view
    get :my_new_device
    post :my_new_device
    get :show_for_approval
    get :approve
    get :reject
    get :suspend        
  end

  


  
end

app/models/device.rb
class Device < ActiveRecord::Base

  ############################################
  ### Constants
  ############################################
  STATES = 
  [
    "Active",   
    "Inactive",
    "SubmittedForReview",
    "Suspended",
    "Old",
  ]

  CATEGORIES =
  [
    "Diagnostic",
    "Fitness / Actographic",
    "Implanted",
    "Drug Delivery / Dispensing",
    "mHealth",
    "Other",
  ]

  ############################################
  ### Callbacks
  ### http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html
  ############################################
  ### before_create :generate_permalink

  ############################################
  ### Validations
  ### http://guides.rubyonrails.org/active_record_validations.html 
  ############################################
  validates_presence_of  :name #, :state
  # validates_uniqueness_of :name
  # validates :id, numericality: {equal_to: 1}  # there should only be one system
  ### validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 80 }
  ### validates :password, length: { in: 6..20 }
  ### validates :registration_number, length: { is: 6 }
  validates_inclusion_of :state, in: self::STATES
  ### validates :size, inclusion: { in: %w(small medium large),  message: "%{value} is not a valid size" }
  ### validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/,   message: "only allows letters" }

  ############################################
  ### Associations
  ### http://guides.rubyonrails.org/association_basics.html
  ############################################
  belongs_to :vendor
  has_many :ct_refs, -> {order 'id'}, dependent: :destroy
  has_many :client_refs, -> {order 'id'}, dependent: :destroy
  has_many :marketing_refs, -> {order 'id'}, dependent: :destroy
  has_many :peer_review_refs, -> {order 'id'}, dependent: :destroy

  # has_and_belongs_to_many :codelocs
  ### has_many :assigned_tasks, :class_name => "Task", :foreign_key => "assigned_user_id"
  ### has_and_belongs_to_many :guardians  ## 2.335
  ### belongs_to :child, :class_name => "Member", :foreign_key => "child_id" ## Self-referential, p2.351
  ### has_many :parents, :class_name => "Member", :foreign_key => "parent_id"  ## Self-referential, p2.351
  ### has_many :blocks, :order => :position ## acts as list ref 2.352
  ### acts_as_list :scope => :block ## acts as list ref 2.352. Run ruby script/plugin install acts_as_list
  ### belongs_to :resource, :polymorphic => true ## polymorphic, ref 2.346
  ### has_one :question, :as => :resource ## 2.324, 2.328

  ############################################
  ### object_class
  ### -- returns an appropriate class for display
  ### -- in_type = 'btn' or 'label'
  ### -- e.g. <span class="<%=device.label_class%>"> <%= device.state %> </span>
  ### -- If you are an evaluator, you only care about 'SubmittedForReview'
  ### -- If you are a Vendor, you want to see all the colours
  ############################################ 
  def object_class(in_current_user, in_type)
	    
    if ["evaluator", "super_user"].include? in_current_user.role 
      if self.state == "SubmittedForReview" 
	label = "danger"
      else
	label = "info"        
      end
    else
      if self.state == "Inactive"
        label = "default"
      elsif self.state == "SubmittedForReview"
        label = "info"
      elsif self.state == "Active"
        label = "success"
      elsif self.state == "Old"
        label = "danger"
      elsif self.state == "Suspended"
        label = "warning"            
      end
    end 	     
    in_type + "-" + label
  end

  
  ############################################
  ### is_this_mine?
  ############################################ 
  def is_this_mine?(in_current_user)

    result = false
    if in_current_user.role == "super_user"
      result = true
    elsif self.vendor.user == in_current_user
      result = true
    end
    result
  end
  
  #################################################################################################
  ### Protected Region: Callbacks [1.p302]
  ################################################################################################# 
  protected

  ############################################
  ### get_all_mine
  ############################################ 
  def self.get_all_mine(in_current_user)
    instances = []
    if in_current_user.try(:super_user?)
      instances = self.all 
    else
      instances << in_current_user.organization.devices      
    end
    instances
  end

  
end

app/controllers/admin/devices_controller.rb
module Admin
  class DevicesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Device.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Device.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy, :my_show]
  before_action :authenticate_user!
  after_action :verify_authorized
  

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.state = "Inactive"
    authorize @device    
    @return_to = params[:return_to]
    respond_to do |format|
      if @device.save
        format.html {
          redirect_to @device, notice: 'Device was successfully created. It is Inactive, and should be submitted for review before it can be published' unless @return_to
          render @return_to          
        }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ###################################
  ### GET /devices/my_show
  ### helper: devices_my_show_path(:id)
  ### params: {"controller"=>"devices", "action"=>"my_show", "id"=>2 }
  ###################################
  def my_show

    authorize @device
    
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      # http://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html
     params[:device].permit(:name, :summary, :description, :website, :category, :contact_name, :contact_email, :comment)            
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_confirm.html.erb
<% # Available: local_assigns[:function], local_assigns[:message], local_assigns[:button_text], local_assigns[:ct_ref], @form_path, @vendor, @return_to, @category_dropdown %>

<% device = Device.find(local_assigns[:id]) %>

  <%= simple_form_for(device, :url => @form_path, :html => {:return_to => @return_to || "", :class => "form-inline"}) do |f| %>

     <%= f.error_notification %>
     <% if device.errors.any? %>
     <ul>
        <% device.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
     </ul>
     <% end %>

    <div class="form-inputs">
    <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 

      <%= hidden_field_tag :device_id, local_assigns[:id] %>        
      <%= hidden_field_tag :function, local_assigns[:function] %>
      <%= hidden_field_tag :return_to, @return_to || "" %>
   
      <label><%= local_assigns[:message] %></label>
      <input class="form-control" id="yes" name="confirm_string">
      
      <div class="form-actions">
        <span class="btn-group-sm" role="group" aria-label="...">
          <%= f.button :submit, class: 'btn btn-danger', :value => local_assigns[:button_text] %>
        </span>
      </div>
    </div>
    
  <% end %>

app/views/devices/_device_card.html.erb
<div class="thumbnail">
  <a href="<%=device.vendor.website%>" target="_blank">
    <img src="<%=device.vendor.logo_path%>"
	 style="float:right; width:100px; margin:5px;" alt="">
  </a>

  <div class="captionzz">
    
    <h3><%=device.name%></h3>
    <%= link_to device.vendor.name, "http://" + device.vendor.website, :target => "_blank"  %>
    
    <p><%=device.summary%></p>

    <div>
      <a href="<%=device.website%>" target="_blank">
	<img class="media-object" style="float:left; height:100px; margin-right:10px;"
	     src="<%=device.image_path%>" alt="...">
      </a>


    </div>
    <p> Category: <%=device.category%></p>
    <p><a href="<%= device_my_show_path(device)  %>" class="btn btn-primary" role="button">Find out more</a>
      <br><br><br>
  </div>
</div>

app/views/devices/_edit.html.erb
<% # Available: @form_path, @vendor, @return_to, @category_dropdown %>

<% device = Device.find(local_assigns[:id]) %>
<% if device.is_this_mine?(current_user) %>

  <%= simple_form_for(device, :url => @form_path, :html => {:return_to => @return_to || ""}) do |f| %>
     <%= f.error_notification %>
     <% if device.errors.any? %>
     <ul>
        <% device.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
     </ul>
     <% end %>

    <div class="form-inputs">
    <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 

      <%= hidden_field_tag :device_id, local_assigns[:id] %>    
      <%= hidden_field_tag :function, "device_edit" %>
      <%= hidden_field_tag :return_to, @return_to || "" %>



      <%= hidden_field_tag :return_to, @return_to || "" %>
   
      <div class="form-group">
        <%= f.label :name %>
        <%= "What is the name of the Device/Service?"  %>
        <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label "Please summarize the device in one line." %>
        <%= ""  %>
        <%= f.text_field :summary, :autofocus => false, class: 'form-control ' %>
      </div>      

      <div class="form-group">
        <%= f.label "You can provide more detail here." %>
        <%= ""  %>
        <%= f.text_area :description, :autofocus => false, class: 'form-control ' %>
      </div>

      <div class="form-group">
        <%= f.label "Is there a web-site for this Device/Service?" %>
        <%= "This should be a specific website, not a general company website."  %>
        <%= f.text_field :website, :autofocus => false, class: 'form-control ' %>
      </div>   

      <div class="form-group">
        <%= f.label :category %>
        <%= "What is the best category for this Device/Service? If there is no match, please select 'No Match'"  %>
        <%= f.select :category, @category_dropdown, :autofocus => false, class: 'form-control'  %>     
      </div>   
   
      <div class="form-group">
        <%= f.label "Who would like to be contacted about this Device/Service?." %>
        <%= "This could be you, a CEO, or a marketing representative, etc.."  %>
        <%= f.text_field :contact_name, :autofocus => false, class: 'form-control ' %>
      </div>

      <div class="form-group">
        <%= f.label "And his/her email address?" %>
        <%= ""  %>
        <%= f.text_field :contact_email, :autofocus => false, class: 'form-control ' %>
      </div>

      <div class="form-group">
	<%= f.label "Please provide a link to an image for this device?" %>
	<%= ""  %>
	<%= f.text_field :image_path, :autofocus => false, class: 'form-control ' %>
      </div>
   
      <div class="form-group">
        <%= f.label "Do you want to add any notes?" %>
        <%= "These are notes to yourself and/or the evaluator of your submission. They will not appear to other users of this registry."  %>
        <%= f.text_area :comment, :autofocus => false, class: 'form-control ' %>
      </div>   
   </div> <!-- form inputs -->

    <div class="form-actions">
      <span class="btn-group-sm" role="group" aria-label="...">
        <%= f.button :submit, class: 'btn btn-info', :value => "Update" %>
      </span>
    </div>
  <% end %>
<% end %>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/_index_public.html.erb
<script>

<% ######################################################################## %>
<% ### Document ready bindings, etc.                                    ### %>
<% ######################################################################## %>

  $(document).ready(function()
  {

  });

     
<% ######################################################################## %>
<% ### Setup javascript                                                  ### %>
<% ######################################################################## %>



<% ######################################################################## %>
<% ### Operational javascript functions                                 ### %>
<% ######################################################################## %>

var searchSelectChanged = function() 
{
   selected = $("#Category option:selected").text();

   if (selected == "")
   {
      window.location.href = "/"
   }
      else
   {
      window.location.href = "/?category=" + selected;
   }
};


</script>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Connected Devices & Services</h3>
  </div>
  <div class="panel-body">  
    <table style="width:100%">
      <tr>
	<td  wwstyle="width:23%">
	  <div style="color:blue; float:right; margin:10px">
	    <%= paginate @devices, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>
	  </div
	</td>
	<td >
	  <span>
	    <div style="width: 76%; margin-left:auto; margin-right:auto;">
	      <%= form_tag request.path, :method => 'get' do %>
	  Search: 
              <%= submit_tag(value = "Vendors", options = {:class => "btn btn-sm  btn-primary"})%>
	      <%= submit_tag(value = "Devices", options = {:class => "btn btn-sm  btn-primary"})%>
	      <%= text_field_tag :search, params[:search], :value => @search, :size => 8 %>		 	      
	      <%= submit_tag(value = "Clear", options = {:class => "btn btn-sm btn-primary"})%>
	    <% end %>
            </div> 
          </span>
        </td>
        <td>
          <span style="float:left; margin:10px">
	    <form class="form-inline">
	      <div class="form-group">
		<label class="sr-only">Category</label>
		<p class="form-control-static">Category: </p>
	      </div>
	      <div class="form-group">
		<%= select_tag "Category", options_for_select(Device::CATEGORIES, params[:category]),
		    {
		    :include_blank => true,
                :onchange => "searchSelectChanged()",
	        :class => "form-control",
                }
		%>
	      </div>
	    </form>
          </span>
        </td>
      </tr> 
    </table>
    <br>  

    <div class="row">
      <% count = 0 %>
      <div>
      <% @devices.each do |device| %>
        <% if count % 3 == 0 %>
          </div><div class="row">
	<% end %>
        <% count += 1 %>	
        <div class="col-sm-6 col-md-4">
        <%= render :partial => "devices/device_card", :locals => { :device => device }%> 
        </div>
      <% end %>
      </div>
    </div>
  </div> <!-- panel -->
</div> <!-- panel-heading -->

app/views/devices/_new.html.erb
<% # Available: @form_path, @vendor, @device, @return_to, @category_dropdown %>

<%= simple_form_for(@device, :url => @form_path, :html => {:return_to => @return_to || ""}) do |f| %>
   <%= f.error_notification %>
   <% if @device.errors.any? %>
   <ul>
      <% @device.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
   </ul>
   <% end %>

<div class="form-inputs">
   <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 

   <%= hidden_field_tag :return_to, @return_to || "" %>
   
   <div class="form-group">
     <%= f.label :name %>
     <%= "What is the name of the Device/Service?"  %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
   </div>

   <div class="form-group">
     <%= f.label "Please summarize the device in one line." %>
     <%= ""  %>
      <%= f.text_field :summary, :autofocus => false, class: 'form-control ' %>
   </div>      

   <div class="form-group">
     <%= f.label "You can provide more detail here." %>
     <%= ""  %>
      <%= f.text_area :description, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "Is there a web-site for this Device/Service?" %>
     <%= "This should be a specific website, not a general company website."  %>
      <%= f.text_field :website, :autofocus => false, class: 'form-control ' %>
   </div>   

   <div class="form-group">
     <%= f.label :category %>
     <%= "What is the best category for this Device/Service? If there is no match, please select 'No Match'"  %>
     <%= f.select :category, @category_dropdown, :autofocus => false, class: 'form-control'  %>     
   </div>   
   
   <div class="form-group">
     <%= f.label "Who would like to be contacted about this Device/Service?." %>
     <%= "This could be you, a CEO, or a marketing representative, etc.."  %>
      <%= f.text_field :contact_name, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "And his/her email address?" %>
     <%= ""  %>
      <%= f.text_field :contact_email, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "Please provide a link to an image for this device?" %>
     <%= ""  %>
      <%= f.text_field :image_path, :autofocus => false, class: 'form-control ' %>
   </div>
   
   <div class="form-group">
     <%= f.label "Do you want to add any notes?" %>
     <%= "These are notes to yourself and/or the evaluator of your submission. They will not appear to other users of this registry."  %>
      <%= f.text_area :comment, :autofocus => false, class: 'form-control ' %>
   </div>   
</div>
   
   <h3> Thank you .... </h3>

<div class="form-actions">
   <span class="btn-group-sm" role="group" aria-label="...">
      <%= f.button :submit, class: 'btn btn-info', :value => "New Device" %>
      <a class="btn btn-success" href="<%= @return_to || root_path %>">Cancel</a>
   </span>
</div>
<% end %>

app/views/devices/_view.html.erb
<% device = Device.find(local_assigns[:id]) %>

      <table class="table table-hover">
         <tbody>
            <tr>
               <td class="col-md-1">Name </td><td><%=device.name%> </td>
            </tr> 
            <tr>
               <td class="col-md-1">Summary </td><td><%=device.summary%> </td>
            </tr>
            <tr>
               <td class="col-md-1">Description </td><td><%=device.description%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Website</td><td><%=device.website%></td>
            </tr>
            <tr>
                <td class="col-md-1">Category</td><td><%=device.category%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Contact Name</td><td><%=device.contact_name%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Contact Email</td><td><%=device.contact_email%> </td>
            </tr>
	    
         </tbody>
      </table>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Devices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/devices/yy_new.html.erb
<% # Available: @vendor, @device, @return_to, @category_dropdown %>

<%= simple_form_for(@device) do |f| %>
   <%= f.error_notification %>
   <% if @device.errors.any? %>
   <ul>
      <% @device.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
   </ul>
   <% end %>

<div class="form-inputs">
   <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 

   <%= f.hidden_field :return_to, :value => @return_to || "" %>
   
   <div class="form-group">
     <%= f.label "What is the name of the Device/Service?" %>
     <%= ""  %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
   </div>

   <div class="form-group">
     <%= f.label "Please summarize the device in one line." %>
     <%= ""  %>
      <%= f.text_field :summary, :autofocus => false, class: 'form-control ' %>
   </div>      

   <div class="form-group">
     <%= f.label "You can provide more detail here." %>
     <%= ""  %>
      <%= f.text_area :description, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "Is there a web-site for this Device/Service?" %>
     <%= "This should be a specific website, not a general company website."  %>
      <%= f.text_field :website, :autofocus => false, class: 'form-control ' %>
   </div>   

   <div class="form-group">
     <%= f.label :category %>
     <%= "What is the best category for this Device/Service? If there is no match, please select 'No Match'"  %>
     <%= f.select :category, @category_dropdown, :autofocus => false, class: 'form-control'  %>     
   </div>   
   
   <div class="form-group">
     <%= f.label "Who would like to be contacted about this Device/Service?." %>
     <%= "This could be you, a CEO, or a marketing representative, etc.."  %>
      <%= f.text_field :contact_name, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "And his/her email address?" %>
     <%= ""  %>
      <%= f.text_field :contact_email, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "Do you want to add any notes?" %>
     <%= "These are notes to yourself and/or the evaluator of your submission. They will not appear to other users of this registry."  %>
      <%= f.text_area :comment, :autofocus => false, class: 'form-control ' %>
   </div>   
      
   <h3> Thank you .... </h3>

<div class="form-actions">
   <span class="btn-group-sm" role="group" aria-label="...">
      <%= f.button :submit, class: 'btn btn-info', :value => "New Device" %>
      <a class="btn btn-success" href="<%= devices_path %>">Cancel</a>
   </span>
</div>
<% end %>