config/routes.rb
Rails.application.routes.draw do

  ##################################
  ### home
  ##################################
  root to: 'visitors#index'

  ##################################
  ### admin (Administrate)
  ##################################
  namespace :admin do

    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    #resources :users 
    #resources :organizations
    #resources :systems
    #resources :vendors
    #resources :devices
    #resources :ct_refs
    #resources :client_refs            
    root to: "users#index"
  end


  ####################
  ### visitors
  ####################
  get 'visitors/super_user_home', to: 'visitors#super_user_home'
  get 'visitors/admin_home', to: 'visitors#admin_home'
  get 'visitors/evaluator_home', to: 'visitors#evaluator_home'
  get 'visitors/vendor_home', to: 'visitors#vendor_home'
  get 'visitors/visitor_home', to: 'visitors#visitor_home'
  get 'visitors/waiting_approval_home', to: 'visitors#waiting_approval_home'
  get 'visitors/suspended_home', to: 'visitors#sustemded_home'      


  ####################
  ### client_refs
  ####################
  resources :client_refs
  # and for my children, allow me to create a new child
  resources "client_refs" do # client_ref_new_XXX_path 
  end

  ####################
  ### ct_refs
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :ct_refs
  # and for my children, allow me to create a new child
  resources "ct_refs" do # ct_ref_new_XXX_path 
  end

  
  ####################
  ### devices
  ####################
  match 'devices/:id/my_show' => 'devices#my_show', :via => :get, :as => 'device_my_show'
  resources :devices
  # and for my children, allow me to create a new child
  resources "devices" do # device_new_XXX_path 
    post :new_ct_ref                           
    post :new_client_ref
    post :new_marketing_ref
    post :new_peer_reviewed_ref
  end
  
  ####################
  ### marketing_refs
  ####################
  resources :marketing_refs
  # and for my children, allow me to create a new child
  resources "marketing_refs" do # marketing_ref_new_XXX_path 
  end

  
  ####################
  ### organizations
  ####################
  resources :organizations
  # and for my children, allow me to create a new child
  resources "organizations" do
    post :new_user                           # organization_new_user_path 
                                             # POST /organizations/:organization_id/new_user(.:format)
    post :new_vendor
    member do
      # get  :register_email_intervention      # register_email_intervention_organization_path 
      #                                        # GET /organizations/:id/register_email_intervention(.:format)
    end
  end

  ####################
  ### peer_review_refs
  ####################
  resources :peer_review_refs
  # and for my children, allow me to create a new child
  resources "peer_review_refs" do # peer_review_ref_new_XXX_path 
  end
  
  
  ####################
  ### systems
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :systems
  # and for my children, allow me to create a new child
  resources "systems" do
    post :new_organization
  end

  ##################################
  ### users
  ##################################
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}  
  # match 'users/for_approval' => 'users#for_approval', :via => :get #, :as => ''
  resources :users


  
  
  ####################
  ### vendors
  ####################
  match 'vendors/request_registration_1' => 'vendors#request_registration_1', :via => :get #, :as => ''
  match 'vendors/request_registration_2' => 'vendors#request_registration_2', :via => [:get] #, :as => ''
  match 'vendors/request_registration_3' => 'vendors#request_registration_3', :via => [:post] #, :as => ''
  match 'vendors/for_approval' => 'vendors#for_approval', :via => :get #, :as => ''
  match 'vendors/devices_for_approval' => 'vendors#devices_for_approval', :via => :get #, :as => ''  
  resources :vendors
  # and for my children, allow me to create a new child
  resources "vendors" do # maps to [vendor_my_view_path] [GET /vendors/:vendor_id/my_view] [vendors#my_view]
    get :my_view
    post :my_view
    patch :my_view
    get :my_new_device
    post :my_new_device
    get :show_for_approval
    get :approve
    get :reject
    get :suspend        
  end

  


  
end

app/controllers/admin/vendors_controller.rb
module Admin
  class VendorsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Vendor.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Vendor.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy, :show_for_approval, :approve, :reject]
  before_action :authenticate_user!
  after_action :verify_authorized
  

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ###################################
  ### GET /vendors/request_registration_1
  ### helper: vendors_request_registration_1_path
  ### params: {"controller"=>"vendors", "action"=>"request_registration_1"}
  ### request_registration_1
  ###################################
  def request_registration_1
    System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")        
    authorize Vendor
    
  end

  ###################################
  ### GET /vendors/request_registration_2
  ### helper: vendors_request_registration_2_path
  ### params: {"controller"=>"vendors", "action"=>"request_registration_2"}
  ### request_registration_2
  ###################################
  def request_registration_2
    System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")
    @vendor = Vendor.new
    authorize @vendor
    
  end

  ###################################
  ### GET /vendors/request_registration_3
  ### helper: vendors_request_registration_3_path
  ### params: {"controller"=>"vendors", "action"=>"request_registration_3"}
  ### request_registration_3
  ###################################
  def request_registration_3
    System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")
    @vendor = Vendor.new(vendor_params)
    @vendor.state = "SubmittedForReview"
    authorize @vendor
    @vendor.user = current_user
    if @vendor.save
      if current_user.role == "visitor"
        current_user.role = "vendor"
        current_user.save
      end
      redirect_to root_path      
    else
      render vendors_request_registration_2_path
      System.uc_controller_log("2.a.RequestVendorRegistration", current_user, controller_path, action_name, "Failed Vendor model validation")      
    end
    System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "Created Vendor=" + @vendor.id.to_s)
  end

  ###################################
  ### GET /vendors/for_approval
  ### helper: vendors_for_approva;_path
  ### params: {"controller"=>"vendors", "action"=>"for_approval"}
  ###################################
  def for_approval
    # System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    # @return_to = visitors_vendor_home_path
    authorize Vendor    
    @vendors = Vendor.where(state: "SubmittedForReview").page(params[:page]).per(8)
    @return_to = params[:return_to] ||= root_path
    
  end

  ###################################
  ### GET /vendors/show_for_approval
  ### helper: vendors_show_for_approval_path(id)
  ### params: {"return_to"=>"uuu", "controller"=>"vendors", "action"=>"show_for_approval", "vendor_id"=>"2", "id"=>"2"}
  ###################################
  def show_for_approval
    # System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    # @return_to = visitors_vendor_home_path
    authorize @vendor   
    @return_to = params[:return_to] ||= root_path    
  end

  ###################################
  ### GET /vendors/approve
  ### helper: vendors_approve_path(id)
  ### params: {"return_to"=>"uuu", "controller"=>"vendors", "action"=>"approve", "vendor_id"=>"2", "id"=>"2"}
  ###################################
  def approve
    # System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    # @return_to = visitors_vendor_home_path
    authorize @vendor
    @vendor.state = "Active"
    if @vendor.save 
      flash[:notice] = "The Vendor #{@vendor.name} has been approved and can now register devices. An email has been sent to the requesting user. "
    else
      flash[:alert] = "The Vendor could not be approved - there was an error"          
    end
    redirect_to params[:return_to] ||= root_path    
  end

  ###################################
  ### GET /vendors/reject
  ### helper: vendors_reject_path(id)
  ### params: {"return_to"=>"uuu", "controller"=>"vendors", "action"=>"reject", "vendor_id"=>"2", "id"=>"2"}
  ###################################
  def reject
    # System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    # @return_to = visitors_vendor_home_path
    authorize @vendor
    @vendor.state = "ApprovalRejected"
    if @vendor.save 
      flash[:notice] = "The Vendor #{@vendor.name} has been rejected and can now register devices. An email has been sent to the requesting user. "
    else
      flash[:alert] = "The Vendor could not be rejected - there was an error"          
    end
    redirect_to params[:return_to] ||= root_path    
  end

  ###################################
  ### GET /vendors/devices_for_approval
  ### helper: vendors_devices_for_approval_path
  ### params: {"controller"=>"vendors", "action"=>"devices_for_approval"}
  ###################################
  def devices_for_approval
    # System.uc_controller_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "")    
    # @return_to = visitors_vendor_home_path
    authorize Vendor

    @vendors_hash = {}

    
    @devices = Device.where(state: "SubmittedForReview")
    @number_of_devices_hash = {}
    for device in @devices
      @vendors_hash[device.vendor.id] = device.vendor
      if @number_of_devices_hash[device.vendor.id] == nil
        @number_of_devices_hash[device.vendor.id] = 1
      else
        @number_of_devices_hash[device.vendor.id] += 1
      end
    end
    
    @ct_refs = CtRef.where(state: "SubmittedForReview")
    @number_of_ct_refs_hash = {}
    for ct_ref in @ct_refs
      @vendors_hash[ct_ref.device.vendor.id] = ct_ref.device.vendor
      if @number_of_ct_refs_hash[ct_ref.device.vendor.id] == nil
        @number_of_ct_refs_hash[ct_ref.device.vendor.id] = 1
      else
        @number_of_ct_refs_hash[ct_ref.device.vendor.id] += 1
      end
    end
    
    @client_refs = ClientRef.where(state: "SubmittedForReview")
    @number_of_client_refs_hash = {}
    for client_ref in @client_refs
      @vendors_hash[client_ref.device.vendor.id] = client_ref.device.vendor
      if @number_of_client_refs_hash[client_ref.device.vendor.id] == nil
        @number_of_client_refs_hash[client_ref.device.vendor.id] = 1
      else
        @number_of_client_refs_hash[client_ref.device.vendor.id] += 1
      end
    end

    ###
    ### This must come last because we're counting vendors
    ###
    @vendors = []
    for key in @vendors_hash.keys
      @vendors << @vendors_hash[key]
    end
    # @vendors = @vendors.page(params[:page]).per(8)
    @vendors = Kaminari.paginate_array(@vendors).page(params[:page]).per(8)
    @return_to = params[:return_to] ||= root_path

  end
  
  
  ###################################
  ### GET /vendors/1/my_view
  ### helper: vendor_my_view_path
  ### GET params: {"controller"=>"vendors", "action"=>"my_view", "vendor_id"=>"22", "return_to"=>"/visitors/super_user_home"}
  ### my_view
  ###################################
  def my_view
    

    #############################
    ### Device-level actions
    #############################
    ### ct_ref_new
    ###
    #############################
    if params[:function] == "ct_ref_new"
      device = Device.find(params[:device_id])      
      if device.is_this_mine?(current_user)
        ct_ref = device.ct_refs.build(ct_ref_params)
        ct_ref.state = "Inactive"
        ct_ref.device = device
        if ct_ref.save
          flash[:notice] = "CT Reference was successfully created"
        else
          flash[:alert] = "CT Reference could not be created: " + ct_ref.errors.full_messages.join(",")
        end
        @ct_refs_hash[device.id] = device.ct_refs
      else
        flash[:alert] = "Error updating device - it's not yours!"
      end
    #############################
    ### client_ref_new
    ###
    #############################
    elsif params[:function] == "client_ref_new"
      device = Device.find(params[:device_id])      
      if device.is_this_mine?(current_user)
        client_ref = device.client_refs.build(client_ref_params)
        client_ref.state = "Inactive"
        client_ref.device = device
        if client_ref.save
          flash[:notice] = "Client Reference was successfully created"

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/_my_list.html.erb
<% # required @variables: @vendors, @return_to %>

   <%= paginate @vendors %>
   <div class="panel panel-default">
      <div class="panel-heading"> 
         <h4>
            You have registered <%= @vendors.length %> Vendors
            <a class="btn btn-info" 
               href="<%= new_vendor_path(return_to: @return_to) %>">
               Register a New Vendor
            </a>
         </h4> 
      </div> <!-- panel-heading -->
      <table class="table table-hover">
         <thead>
            <tr>
               <th>Name</th>
               <th>Division</th>	      
               <th>State</th>
               <th></th>
            </tr>
         </thead>
         <tbody>
            <% @vendors.each do |vendor| %>
               <tr valign="top" class="<%= cycle('list-line-odd', 'list-line-even') %>">
                  <td width="">         
                    <a href=<%=vendor_path(vendor.id)%> > <%= vendor.name %> </a>
                  </td>
                  <td width="">         
                    <%= vendor.division %> 
                  </td>
                  <td width="">         
                    <%= vendor.state %>
                  <td width="35%" align="left"> 
                     <% if vendor.state == "Active"  %>
                        <%= link_to 'Deactivate', vendor_suspend_path(vendor.id, :return_to => @return_to),  
                                :class => 'btn btn-warning btn-xs'  %>
                     <% end %>
                     <% if vendor.state == "Inactive"  %>
                        <%= link_to 'Activate', vendor_activate_path(vendor.id, :return_to => @return_to),  
                                :class => 'btn btn-warning btn-xs'  %>
                     <% end %>
                     <%= link_to 'View', vendor_path(vendor.id, :return_to => @return_to),  :class => 'btn btn-success btn-xs' %>
                     <%= link_to 'Edit', edit_vendor_path(vendor.id, :return_to => @return_to),  :class => 'btn btn-info btn-xs' %>
                     <%= link_to("Delete", vendor_path(vendor, :return_to => @return_to), :data => { :confirm => "Are you sure?" }, 
                                :method => :delete, :class => 'btn btn-danger btn-xs') %>

                  </td>
                </tr>
            <%end%>
         </tbody>
      </table>
   </div> <!-- panel -->

app/views/vendors/_waiting_for_approval.html.erb
<% # required @variables: @vendor %>

<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  Please wait while your registration of <b><%= @vendor.name %> is processed</b>. This should take up to 5 working days.<br>
  Once registration has been completed you can then submit your devices and/or services for inclusion in the Registry. 
</div>

app/views/vendors/devices_for_approval.html.erb
<div class="container">
   <%= paginate @vendors, :theme => 'twitter-bootstrap-3' %>
   <div class="panel panel-default">
      <div class="panel-heading"> <h4>Listing Vendors with outstanding approval requests</h4>
         <%= link_to 'Back', @return_to ||= root_path, :class => 'btn btn-success btn-xs' %>
       
      </div> <!-- panel-heading -->
      <table class="table table-hover">
         <col >
         <col >
         <col >
         <col >
         <col >
         <col width="20%">

         <thead>

            <tr>
              <th>Vendor Name</th>
              <th>Devices</th>
              <th>CT References</th>
              <th>Client References</th>	      	      
              <th>
                  <span class="btn-group btn-group-sm" role="group" aria-label="...">

                  </span>
               </th>
            </tr>
         </thead>
         <tbody>
            <% @vendors.each do |vendor| %>
               <tr>
                  <td><%= vendor.name.truncate(30) %></td>
                  <td><%= @number_of_devices_hash[vendor.id].to_s %></td>
                  <td><%= @number_of_ct_refs_hash[vendor.id].to_s %></td>
                  <td><%= @number_of_client_refs_hash[vendor.id].to_s %></td>		  		  
                  <td>
                     <%= link_to 'Show', vendor_my_view_path(vendor, :return_to => @return_to ||= root_path), :class => 'btn btn-success btn-xs' %>
                  </td>
               </tr>
            <% end %>
         </tbody>
      </table>
   </div> <!-- panel -->
</div> <!-- container -->

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<div class="container">
   <%= paginate @vendors %>
   <div class="panel panel-default">
      <div class="panel-heading"> <h4>Listing Vendors</h4> 
         <a class="btn btn-info" href="<%= new_vendor_path %>">New</a>
         <a class="btn btn-info" href="<%= vendors_new_empty_vendor_path %>">New Empty Vendor</a>
      </div> <!-- panel-heading -->
      <table class="table table-hover">
         <col >
         <col >
         <col >
         <col >
         <col >
         <col width="20%">

         <thead>

            <tr>
              <th>Name</th>
               <th>State</th>
               <th>Comment</th>
               <th>Organization</th>
               <th>
                  <span class="btn-group btn-group-sm" role="group" aria-label="...">

                  </span>
               </th>
            </tr>
         </thead>
         <tbody>
            <% @vendors.each do |vendor| %>
               <tr>
                  <td><%= vendor.id %></td>
                  <td><%= vendor.name %></td>
                  <td><%= vendor.state %></td>
                  <td><%= vendor.comment.truncate(80) %></td>
                  <td>  <a href="<%= organization_path(vendor.organization.id) if vendor.organization %>"> <%= vendor.organization.name if vendor.organization %> </a>
                  </td>

                  <td>
                     <%= link_to 'Design', vendor_design_path(vendor),  :class => '' %>
                     <%= link_to 'Show', vendor_path(vendor),  :class => '' %>
                     <%= link_to 'Edit', edit_vendor_path(vendor),  :class => '' %>
                     <%= link_to("Delete", vendor_path(vendor), :data => { :confirm => "Are you sure?" }, 
                                :method => :delete, :class => '') %>
                  </td>
               </tr>
            <% end %>
         </tbody>
      </table>
   </div> <!-- panel -->
</div> <!-- container -->

app/views/vendors/my_new_device.html.erb
<% # Available: @vendor, @return_to, @category_dropdown, @device %>



<h3>New Device/Service for Vendor <%= @vendor.name %></h3>

<%= render :partial => "devices/new" %>

app/views/vendors/request_registration_2.html.erb
<% System.uc_view_log("2.RequestVendorRegistration", current_user, controller_path, action_name, "") %>

<h3>Tell us the following about your vendor organization: </h3>


<%= simple_form_for(@vendor, url: vendors_request_registration_3_path) do |f| %>
   <%= f.error_notification %>
   <% if @vendor.errors.any? %>
   <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
   </ul>
   <% end %>

<div class="form-inputs">
   <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 
   
   <div class="form-group">
     <%= f.label "What is the name of your organization?" %>
     <%= "This is probably your company name"  %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
   </div>

   <div class="form-group">
     <%= f.label "What is the name of the division or group within your organization?" %>
     <%= "This is optional, but expected for larger corporations."  %>
      <%= f.text_field :division, :autofocus => false, class: 'form-control ' %>
   </div>   

   <div class="form-group">
     <%= f.label "What is your web-site?" %>
     <%= "We would prefer the website of your group/division if there is one."  %>
      <%= f.text_field :website, :autofocus => false, class: 'form-control ' %>
   </div>   

   <div class="form-group">
     <%= f.label "What is your organization's LinkedIn page URL?" %>
     <%= "This is optional. Please trim the characters after the first '?'"  %>
      <%= f.text_field :linkedin, :autofocus => false, class: 'form-control ' %>
   </div>   

   <div class="form-group">
     <%= f.label "Please summarize your organization's / division's / group's business in one line." %>
     <%= "We're not referring to the device / service yet - keep it high-level."  %>
      <%= f.text_field :summary, :autofocus => false, class: 'form-control ' %>
   </div>      

   <div class="form-group">
     <%= f.label "You can provide more detail here." %>
     <%= "Concrete information, please. A reader should understand your business after reading this. You will have an opportunity later to give a lot of information on your device / service, so please keep this description more general"  %>
      <%= f.text_area :description, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "Who's the best contact." %>
     <%= "This could be you, a CEO, or a marketing representative, etc.."  %>
      <%= f.text_field :contact_name, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "And his/her email address?" %>
     <%= ""  %>
      <%= f.text_field :contact_email, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label "Please provide a full path to your company logo" %>
     <%= ""  %>
      <%= f.text_field :logo_path, :autofocus => false, class: 'form-control ' %>
   </div>
   
   <div class="form-group">
     <%= f.label "Do you want to add any notes?" %>
     <%= "These are notes to yourself and/or the evaluator of your submission. They will not appear to other users of this registry."  %>
      <%= f.text_area :comment, :autofocus => false, class: 'form-control ' %>
   </div>   
      
   <h3> Thank you .... </h3>

<div class="form-actions">
   <span class="btn-group-sm" role="group" aria-label="...">
      <%= f.button :submit, class: 'btn btn-info', :value => "Complete Registration" %>
      <a class="btn btn-success" href="<%= vendors_path %>">Cancel</a>
   </span>
</div>
<% end %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/show_for_approval.html.erb
<div class="container">
   <div class="panel panel-default">
      <div class="panel-heading"> <h4>Vendor: <%=@vendor.name%></h4>
        <span class="btn-group-sm" role="group" aria-label="...">
            <%= link_to 'Approve', vendor_approve_path(@vendor, :return_to => @return_to ||= root_path),  :class => 'btn btn-primary btn-xs' %>
            <%= link_to 'Reject', vendor_reject_path(@vendor, :return_to => @return_to ||= root_path), :class => 'btn btn-warning btn-xs' %>
            <%= link_to 'Cancel & Back', :back, :class => 'btn btn-success btn-xs' %>
         </span> <!-- btn-group-sm -->
      </div> <!-- panel-heading -->

      <table class="table table-hover">

         <tbody>
            <tr>
               <td class="col-md-1">Name </td><td><%=@vendor.name%> </td>
            </tr>
            <tr>
               <td class="col-md-1">Division </td><td><%=@vendor.division%> </td>
            </tr>
            <tr>
     
                <td class="col-md-1">Comment</td><td><%=@vendor.comment%> </td>
            </tr>
            <tr>
               <td class="col-md-1">Website </td><td><a href=<%=@vendor.website%> ><%=@vendor.website%></a> </td>
            </tr>
            <tr>
                <td class="col-md-1">LinkedIn</td><td><%=@vendor.linkedin%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Summary</td><td><%=@vendor.summary%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Description</td><td><%=@vendor.description%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Contact Name</td><td><%=@vendor.linkedin%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Contact Email</td><td><%=@vendor.linkedin%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Submitted By</td><td><%=@vendor.user.name%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Submitted On</td><td><%=@vendor.updated_at%> </td>
            </tr>
         </tbody>
      </table>
   </div> <!-- panel -->
</div> <!-- container -->