config/routes.rb
Rails.application.routes.draw do

  ##################################
  ### home
  ##################################
  root to: 'visitors#index'

  ##################################
  ### admin (Administrate)
  ##################################
  namespace :admin do

    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    #resources :users 
    #resources :organizations
    #resources :systems
    #resources :vendors
    #resources :devices
    #resources :ct_refs
    #resources :client_refs            
    root to: "users#index"
  end


  ####################
  ### visitors
  ####################
  get 'visitors/super_user_home', to: 'visitors#super_user_home'
  get 'visitors/admin_home', to: 'visitors#admin_home'
  get 'visitors/evaluator_home', to: 'visitors#evaluator_home'
  get 'visitors/vendor_home', to: 'visitors#vendor_home'
  get 'visitors/visitor_home', to: 'visitors#visitor_home'
  get 'visitors/waiting_approval_home', to: 'visitors#waiting_approval_home'
  get 'visitors/suspended_home', to: 'visitors#sustemded_home'      


  ####################
  ### client_refs
  ####################
  resources :client_refs
  # and for my children, allow me to create a new child
  resources "client_refs" do # client_ref_new_XXX_path 
  end

  ####################
  ### ct_refs
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :ct_refs
  # and for my children, allow me to create a new child
  resources "ct_refs" do # ct_ref_new_XXX_path 
  end

  
  ####################
  ### devices
  ####################
  match 'devices/:id/my_show' => 'devices#my_show', :via => :get, :as => 'device_my_show'
  resources :devices
  # and for my children, allow me to create a new child
  resources "devices" do # device_new_XXX_path 
    post :new_ct_ref                           
    post :new_client_ref
    post :new_marketing_ref
    post :new_peer_reviewed_ref
  end
  
  ####################
  ### marketing_refs
  ####################
  resources :marketing_refs
  # and for my children, allow me to create a new child
  resources "marketing_refs" do # marketing_ref_new_XXX_path 
  end

  
  ####################
  ### organizations
  ####################
  resources :organizations
  # and for my children, allow me to create a new child
  resources "organizations" do
    post :new_user                           # organization_new_user_path 
                                             # POST /organizations/:organization_id/new_user(.:format)
    post :new_vendor
    member do
      # get  :register_email_intervention      # register_email_intervention_organization_path 
      #                                        # GET /organizations/:id/register_email_intervention(.:format)
    end
  end

  ####################
  ### peer_review_refs
  ####################
  resources :peer_review_refs
  # and for my children, allow me to create a new child
  resources "peer_review_refs" do # peer_review_ref_new_XXX_path 
  end
  
  
  ####################
  ### systems
  ####################
  #match 'systems/:id/start_scheduler' => 'systems#start_scheduler', :via => :get, :as => 'system_start_scheduler'
  resources :systems
  # and for my children, allow me to create a new child
  resources "systems" do
    post :new_organization
  end

  ##################################
  ### users
  ##################################
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}  
  # match 'users/for_approval' => 'users#for_approval', :via => :get #, :as => ''
  resources :users


  
  
  ####################
  ### vendors
  ####################
  match 'vendors/request_registration_1' => 'vendors#request_registration_1', :via => :get #, :as => ''
  match 'vendors/request_registration_2' => 'vendors#request_registration_2', :via => [:get] #, :as => ''
  match 'vendors/request_registration_3' => 'vendors#request_registration_3', :via => [:post] #, :as => ''
  match 'vendors/for_approval' => 'vendors#for_approval', :via => :get #, :as => ''
  match 'vendors/devices_for_approval' => 'vendors#devices_for_approval', :via => :get #, :as => ''  
  resources :vendors
  # and for my children, allow me to create a new child
  resources "vendors" do # maps to [vendor_my_view_path] [GET /vendors/:vendor_id/my_view] [vendors#my_view]
    get :my_view
    post :my_view
    patch :my_view
    get :my_new_device
    post :my_new_device
    get :show_for_approval
    get :approve
    get :reject
    get :suspend        
  end

  


  
end

app/models/client_ref.rb
class ClientRef < ActiveRecord::Base


  ############################################
  ### Constants
  ############################################
  STATES = 
  [
    "Active",   
    "Inactive",
    "SubmittedForReview",
    "Suspended",
    "Old",
  ]

  ############################################
  ### Callbacks
  ### http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html
  ############################################
  ### before_create :generate_permalink

  ############################################
  ### Validations
  ### http://guides.rubyonrails.org/active_record_validations.html 
  ############################################
  validates_presence_of  :name #, :state
  validates_uniqueness_of :name
  # validates :id, numericality: {equal_to: 1}  # there should only be one system
  ### validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 80 }
  ### validates :password, length: { in: 6..20 }
  ### validates :registration_number, length: { is: 6 }
  validates_inclusion_of :state, in: self::STATES
  ### validates :size, inclusion: { in: %w(small medium large),  message: "%{value} is not a valid size" }
  ### validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/,   message: "only allows letters" }

  ############################################
  ### Associations
  ### http://guides.rubyonrails.org/association_basics.html
  ############################################
  belongs_to :device
  # has_many :users

  # has_and_belongs_to_many :codelocs
  ### has_many :assigned_tasks, :class_name => "Task", :foreign_key => "assigned_user_id"
  ### has_and_belongs_to_many :guardians  ## 2.335
  ### belongs_to :child, :class_name => "Member", :foreign_key => "child_id" ## Self-referential, p2.351
  ### has_many :parents, :class_name => "Member", :foreign_key => "parent_id"  ## Self-referential, p2.351
  ### has_many :blocks, :order => :position ## acts as list ref 2.352
  ### acts_as_list :scope => :block ## acts as list ref 2.352. Run ruby script/plugin install acts_as_list
  ### belongs_to :resource, :polymorphic => true ## polymorphic, ref 2.346
  ### has_one :question, :as => :resource ## 2.324, 2.328


  ############################################
  ### object_class
  ### -- returns an appropriate class for display
  ### -- in_type = 'btn' or 'label'
  ### -- e.g. <span class="<%=device.label_class%>"> <%= device.state %> </span>
  ### -- If you are an evaluator, you only care about 'SubmittedForReview'
  ### -- If you are a Vendor, you want to see all the colours
  ############################################ 
  def object_class(in_current_user, in_type)
	    
    if ["evaluator", "super_user"].include? in_current_user.role 
      if self.state == "SubmittedForReview" 
	label = "danger"
      else
	label = "info"        
      end
    else
      if self.state == "Inactive"
        label = "default"
      elsif self.state == "SubmittedForReview"
        label = "info"
      elsif self.state == "Active"
        label = "success"
      elsif self.state == "Old"
        label = "danger"
      elsif self.state == "Suspended"
        label = "warning"            
      end
    end 	     
    in_type + "-" + label
  end

  ############################################
  ### label_class
  ### -- returns an appropriate class for display
  ### -- e.g. <span class="<%=device.label_class%>"> <%= device.state %> </span>
  ### -- If you are an evaluator, you only care about 'SubmittedForReview'
  ### -- If you are a Vendor, you want to see all the colours
  ############################################ 
  def label_class(in_current_user)
	    
    if ["evaluator", "super_user"].include? in_current_user.role 
      if self.state == "SubmittedForReview" 
	label = "label-danger"
      else
	label = "label-info"        
      end
    else
      if self.state == "Inactive"
        label = "label-default"
      elsif self.state == "SubmittedForReview"
        label = "label-info"
      elsif self.state == "Active"
        label = "label-success"
      elsif self.state == "Old"
        label = "label-danger"
      elsif self.state == "Suspended"
        label = "label-warning"            
      end
    end 	     
    label
  end
  
  
  ############################################
  ### is_this_mine?
  ############################################ 
  def is_this_mine?(in_current_user)

    result = false
    if in_current_user.role == "super_user"
      result = true
    elsif self.device.vendor.user == in_current_user
      result = true
    end
    result
  end

  #################################################################################################
  ### Protected Region: Callbacks [1.p302]
  ################################################################################################# 
  protected

  ############################################
  ### get_all_mine
  ############################################ 
  def self.get_all_mine(in_current_user)
    instances = []
    if in_current_user.try(:super_user?)
      instances = self.all 
    else
      instances << in_current_user.organization.client_refs      
    end
    instances
  end



  
end

app/controllers/admin/client_refs_controller.rb
module Admin
  class ClientRefsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ClientRef.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ClientRef.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/client_refs_controller.rb
class ClientRefsController < ApplicationController
  before_action :set_client_ref, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized
  

  # GET /client_refs
  # GET /client_refs.json
  def index
    @client_refs = ClientRef.all
  end

  # GET /client_refs/1
  # GET /client_refs/1.json
  def show
  end

  # GET /client_refs/new
  def new
    @client_ref = ClientRef.new
  end

  # GET /client_refs/1/edit
  def edit
  end

  # POST /client_refs
  # POST /client_refs.json
  def create
    @client_ref = ClientRef.new(client_ref_params)

    respond_to do |format|
      if @client_ref.save
        format.html { redirect_to @client_ref, notice: 'Client ref was successfully created.' }
        format.json { render :show, status: :created, location: @client_ref }
      else
        format.html { render :new }
        format.json { render json: @client_ref.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_refs/1
  # PATCH/PUT /client_refs/1.json
  def update
    respond_to do |format|
      if @client_ref.update(client_ref_params)
        format.html { redirect_to @client_ref, notice: 'Client ref was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_ref }
      else
        format.html { render :edit }
        format.json { render json: @client_ref.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_refs/1
  # DELETE /client_refs/1.json
  def destroy
    @client_ref.destroy
    respond_to do |format|
      format.html { redirect_to client_refs_url, notice: 'Client ref was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_ref
      @client_ref = ClientRef.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_ref_params
      params.fetch(:client_ref, {})
    end
end

app/helpers/client_refs_helper.rb
module ClientRefsHelper
end

app/views/client_refs/_client_ref_card.html.erb
       <div class="thumbnail">
         <!-- img src="..." alt="..." -->
         <div class="caption">
           <h3><%=client_ref.name%></h3>
       	   <%= link_to(client_ref.website, client_ref.website, :target => "_blank") %>
	   <h5> Summary </h5>
           <p><%=client_ref.summary.truncate(200)%></p>
	   <h5> Description</h5>	   
           <p><%=client_ref.description.truncate(400)%></p>
           <p><a href="<%=  %>" class="btn btn-primary" role="button">Find out more</a> 
         </div>
       </div>

app/views/client_refs/_confirm.html.erb
<% # Available: local_assigns[:function], local_assigns[:message], local_assigns[:button_text], local_assigns[:client_ref], @form_path, @vendor, @return_to, @category_dropdown %>

<% client_ref = ClientRef.find(local_assigns[:id]) %>

  <%= simple_form_for(client_ref, :url => @form_path, :html => {:return_to => @return_to || "", :class => "form-inline"}) do |f| %>

     <%= f.error_notification %>
     <% if client_ref.errors.any? %>
     <ul>
        <% client_ref.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
     </ul>
     <% end %>

    <div class="form-inputs">
    <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 

      <%= hidden_field_tag :client_ref_id, local_assigns[:id] %>    
      <%= hidden_field_tag :function, local_assigns[:function] %>
      <%= hidden_field_tag :return_to, @return_to || "" %>
   
      <label><%= local_assigns[:message] %></label>
      <input class="form-control" id="yes" name="confirm_string">
      
      <div class="form-actions">
        <span class="btn-group-sm" role="group" aria-label="...">
          <%= f.button :submit, class: 'btn btn-danger', :value => local_assigns[:button_text] %>
        </span>
      </div>
    </div>
    
  <% end %>

app/views/client_refs/_edit.html.erb
<% # Available: @form_path, @vendor, @return_to, @category_dropdown %>

<% client_ref = ClientRef.find(local_assigns[:id]) %>
<% if client_ref.is_this_mine?(current_user) %>

  <%= simple_form_for(client_ref, :url => @form_path, :html => {:return_to => @return_to || ""}) do |f| %>
     <%= f.error_notification %>
     <% if client_ref.errors.any? %>
     <ul>
        <% client_ref.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
     </ul>
     <% end %>

    <div class="form-inputs">
    <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 

      <%= hidden_field_tag :client_ref_id, local_assigns[:id] %>    
      <%= hidden_field_tag :function, "client_ref_edit" %>
      <%= hidden_field_tag :return_to, @return_to || "" %>

  
      <div class="form-group">
        <%= f.label :name %>
        <%= "What is the name of the Client?"  %>
         <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :division %>
        <%= "Is there a relevent Client Division/Business Unit/Group?"  %>
         <%= f.text_field :division, :autofocus => false, class: 'form-control' %>
      </div>
   
   
      <div class="form-group">
        <%= f.label :website %>
        <%= "Provide the most relevent website."  %>
         <%= f.text_field :website, :autofocus => false, class: 'form-control ' %>
      </div>

      <div class="form-group">
        <%= f.label :summary %>
        <%= "Summarise their use of the Device/Service in one line."  %>
         <%= f.text_field :description, :autofocus => false, class: 'form-control ' %>
      </div>
   
      <div class="form-group">
        <%= f.label :description %>
        <%= "You can provide more detail here."  %>
         <%= f.text_area :description, :autofocus => false, class: 'form-control ' %>
     </div>

      <div class="form-group">
        <%= f.label :contact_name %>
        <%= "If permitted, provide a Client reference name."  %>
         <%= f.text_field :contact_name, :autofocus => false, class: 'form-control ' %>
      </div>

      <div class="form-group">
        <%= f.label :contact_email %>
        <%= "If permitted, what is the reference's email?"  %>
         <%= f.text_field :contact_email, :autofocus => false, class: 'form-control ' %>
      </div>
   
      <div class="form-group">
        <%= f.label :permitted %>
        <%= "Confirm that you are permitted to by your client to share this information."  %>
        <%= f.check_box :permitted, :autofocus => false, class: 'form-control ' %>
     </div>
   
   </div> <!-- div class="form-inputs" -->

   <div class="form-actions">
     <span class="btn-group-sm" role="group" aria-label="...">
       <%= f.button :submit, class: 'btn btn-info', :value => "Update" %>
     </span>
   </div>
  <% end %> <%# simple_form_for %>
<% end %> <%# <% if client_ref.is_this_mine?(current_user) %>

app/views/client_refs/_form.html.erb
<%= form_for(@client_ref) do |f| %>
  <% if @client_ref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client_ref.errors.count, "error") %> prohibited this client_ref from being saved:</h2>

      <ul>
      <% @client_ref.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/client_refs/_new.html.erb
<% # Available: @form_path, @vendor, @return_to %>

<% @client_ref = ClientRef.new %>
<% @client_ref.permitted  = false %>

<%= simple_form_for(@client_ref, :url => @form_path, :html => {:return_to => @return_to || ""}) do |f| %>
   <%= f.error_notification %>
   <% if @client_ref.errors.any? %>
   <ul>
      <% @client_ref.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
   </ul>
   <% end %>

<div class="form-inputs">
   <!-- form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-url_field --> 

   <%= hidden_field_tag :device_id, local_assigns[:device_id] %>
   <%= hidden_field_tag :function, "client_ref_new" %>
   <%= hidden_field_tag :return_to, @return_to || "" %>
  
   <div class="form-group">
     <%= f.label :name %>
     <%= "What is the name of the Client?"  %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
   </div>

   <div class="form-group">
     <%= f.label :division %>
     <%= "Is there a relevent Client Division/Business Unit/Group?"  %>
      <%= f.text_field :division, :autofocus => false, class: 'form-control' %>
   </div>
   
   
   <div class="form-group">
     <%= f.label :website %>
     <%= "Provide the most relevent website."  %>
      <%= f.text_field :website, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label :summary %>
     <%= "Summarise their use of the Device/Service in one line."  %>
      <%= f.text_field :description, :autofocus => false, class: 'form-control ' %>
   </div>
   
   <div class="form-group">
     <%= f.label :description %>
     <%= "You can provide more detail here."  %>
      <%= f.text_area :description, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label :contact_name %>
     <%= "If permitted, provide a Client reference name."  %>
      <%= f.text_field :contact_name, :autofocus => false, class: 'form-control ' %>
   </div>

   <div class="form-group">
     <%= f.label :contact_email %>
     <%= "If permitted, what is the reference's email?"  %>
      <%= f.text_field :contact_email, :autofocus => false, class: 'form-control ' %>
   </div>
   
   <div class="form-group">
     <%= f.label :permitted %>
     <%= "Confirm that you are permitted to by your client to share this information."  %>
      <%= f.check_box :permitted, :autofocus => false, class: 'form-control ' %>
   </div>
   
</div>   

<div class="form-actions">
   <span class="btn-group-sm" role="group" aria-label="...">
      <%= f.button :submit, class: 'btn btn-info', :value => "New Client Reference" %>
   </span>
</div>
<% end %>

app/views/client_refs/_view.html.erb
<% client_ref = ClientRef.find(local_assigns[:id]) %>

      <table class="table table-hover">

         <tbody>
            <tr>
               <td class="col-md-1">Name </td><td><%=client_ref.name%> </td>
            </tr> 
            <tr>
               <td class="col-md-1">Division </td><td><%=client_ref.division%> </td>
            </tr>
            <tr>
               <td class="col-md-1">Website </td><td><%=client_ref.website%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Summary</td><td><%=client_ref.summary%></td>
            </tr>
            <tr>
                <td class="col-md-1">Description</td><td><%=client_ref.description%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Contact Name</td><td><%=client_ref.contact_name%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Contact Email</td><td><%=client_ref.contact_email%> </td>
            </tr>
            <tr>
                <td class="col-md-1">Permitted</td><td><%="Yes" if client_ref.permitted %><%="No" unless client_ref.permitted %> </td>
            </tr>
	    
         </tbody>
      </table>

app/views/client_refs/edit.html.erb
<h1>Editing Client Ref</h1>

<%= render 'form' %>

<%= link_to 'Show', @client_ref %> |
<%= link_to 'Back', client_refs_path %>

app/views/client_refs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Client Refs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_refs.each do |client_ref| %>
      <tr>
        <td><%= link_to 'Show', client_ref %></td>
        <td><%= link_to 'Edit', edit_client_ref_path(client_ref) %></td>
        <td><%= link_to 'Destroy', client_ref, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client ref', new_client_ref_path %>

app/views/client_refs/new.html.erb
<h1>New Client Ref</h1>

<%= render 'form' %>

<%= link_to 'Back', client_refs_path %>

app/views/client_refs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_client_ref_path(@client_ref) %> |
<%= link_to 'Back', client_refs_path %>